### ISSUE TITLE
should we gitignore package-lock.json ?

### ISSUE THREAD

**Issue by tawfiknasser** [FACN4/Election-Day-App#13]
as you see, our two package-lock.json files now are 14k lines.
should we gitignore package-lock.json ? 
how that will affect our process in the future ?

**Comment by Karyum** [comment]
package-lock files saves your dependency versions to the point where your project was functioning as an example imagine you build an app and downloaded loads of dependencies and made it work, then you left it for like 4 months by that time some dependencies in your project got updated, and from those update when you do `npm i` you gonna get the new one and high chances your code might now work.
so package-lockk prevents that by saving the older versions so then when you do `npm i` you would download the older ones not the new ones ( the ones that your app was functioning on )
https://docs.npmjs.com/files/package-locks

**Comment by Karyum** [comment]
sorry that was a lengthy answer :sweat_smile:

**Comment by shiryz** [comment]
What @Karyum said!

**Comment by tawfiknasser** [comment]
Thanks you Mario, 
We are keeping the files.
