### ISSUE TITLE
User Testing: (06-09-2018)

### ISSUE THREAD

**Issue by yoosefkh** [FACN4/Election-Day-App#3]
**Template** 
- Users name.
- Users top three pain points using application.
- Users profile.
- Additional observations section.
_________________________
The tasks for the user on box : 
log in ,
understand your task.
in more detailed : 
log in 
search for someone ...
mark the lead
log out
_________________________

**Comment by yoosefkh** [comment]
Users name : Mario

Users top three pain points using application :  
1- He wanted to see all the voters he selected.
2- people who didn't voted yet !

Users profile : User On Box

**Comment by yoosefkh** [comment]
Users name : Jem

Users top three pain points using application :
1-sometimes she click without notice, she want to see message and confirm her click.  
2- Blue and Red  doesn't come along.
Users profile : User On Box

**Comment by yoosefkh** [comment]
Users name : 
Ben

Users top three pain points using application:
want a place holder on the search input 

Users profile : 
User On Box

**Comment by tawfiknasser** [comment]
**Action points :** 
- confirm message when clicking.
- change the colours , more bright.
