### ISSUE TITLE
Update voter status query (user on box)

### ISSUE THREAD

**Issue by Ryan2601** [FACN4/Election-Day-App#34]
We have 3 options for voters status:

1. Didn't vote yet.
2. Didn't vote and we (election HQ) approached him.
3. Voted.

The default value in the DB is 1. For we are doing user on box implementation this query updates the status from to 3 - as from didn't vote yet to voted.

So this query takes id of voter and update the status from 1 to 3.

**Comment by tawfiknasser** [comment]
:+1:
