### ISSUE TITLE
Change DB schema

### ISSUE THREAD

**Issue by Ryan2601** [FACN4/Election-Day-App#35]
After we started implementing the queries we noticed that its better to change the 3 name fields in the voters table (first, middle, last) to one full name field which will help us in the search process.

This will require changes to 3 files:
1. build.sql file - replacing the three name fields into one full name field.
2. insertVoters.js - changing the columns which we want to insert to (again from 3 name fields into 1).
3. insertVotersToDB - while looping over the voters array to combine the name fields into one full name field and sending only full name to the query (insertVoters).

**Comment by yoosefkh** [comment]
![screenshot from 2018-09-12 15-44-50](https://user-images.githubusercontent.com/37940433/45425763-fcfa0100-b6a2-11e8-91f4-7dbd9d8e2dfa.png)
New Database schema
