### ISSUE TITLE
set cookie

### ISSUE THREAD

**Issue by tawfiknasser** [FACN4/Election-Day-App#81]
setting up cookies for login ,
adding username & box number encrypted using JWT

**Comment by Karyum** [comment]
@tawfiknasser 25 minutes ago this issue was raised, 20 min ago the pull request was made if my math is right you raised this issue after you have done all the code.

**Comment by tawfiknasser** [comment]
@Karyum your math is right but looks like yougot problem in your browser time settings :laughing: 
![a05d51d2-1adb-44a4-a54d-476a1cac7707](https://user-images.githubusercontent.com/36166288/45691608-a177b980-bb61-11e8-81e8-356070833f0e.jpeg)

**Comment by haydnba** [comment]
Lol

**Comment by Karyum** [comment]
![screenshot from 2018-09-18 17-38-20](https://user-images.githubusercontent.com/24195641/45695253-b8baa500-bb69-11e8-9a06-79495f6f2533.png)

**Comment by Karyum** [comment]
OMG did you change it in the developer tools in chrome ?!

**Comment by Karyum** [comment]
i bet you did
